### PR TITLE
Fix mulitiline strings

### LINKED ISSUE #110: Multiline strings strings aren't escaped properly
Input:

```
"""
"
"""
```

Output:

```
'\\"'
```

Expected output:

```
'"'
```

### PR DESCRIPTION
**Pull request by juliankrispel**
fixes #110

### CODE REVIEW

**Comment by bouk** [comment]
Should probably open an issue to try and find the proper fox, because there's genuine use cases for this

**Comment by juliankrispel** [comment]
That'd be awesome mate knock yourself out :)

Julian Krispel-Samsel
rainforestqa.com
goodafternoon.co

File: src/parser.js [hunk 1]
```diff
@@ -1391,12 +1391,20 @@ export function transpile(ast, meta) {
...
+  return compiled;
+}
+
 export function compile(source, opts, parse = coffeeParse) {
   const doubleSemicolon = /\;+/g;
   opts = opts || {tabWidth: 2, quote: 'double'};
 
   const _compile = compose(
     // hack because of double semicolon
+    removeDoubleEscapes,
```
Comment (eventualbuddha) [inline src/parser.js]: This should be above the comment since the comment refers to the line below.
